### ISSUE TITLE
Merging app and WebView visits

### ISSUE THREAD

**Issue by hannahcx** [matomo-org/matomo-sdk-android#289] opened 2020-07-30 07:54 UTC
iOS when tracking pages seems to work correctly, telling me how long I spent in app; however, android tells me I spent 1s in app no matter how long I spent clicking through pages. Can you help?

**Comment by d4rken** [comment] 2020-07-30 09:15
Time spent on a page is calculated server-side, from one view event to the next:
https://matomo.org/faq/how-to/faq_21158/

**Comment by hannahcx** [comment] 2020-07-30 09:20
No, as in it doesn't work :) not a question this is a bug! For android.

**Comment by d4rken** [comment] 2020-07-30 09:24
It works for me :tm: :sweat_smile:. Please share a minimal sample project to reproduce the bug.

**Comment by hannahcx** [comment] 2020-07-30 09:44
I think the issue is that we use webviews inside the app, but the webviews are not registering as the same session. Any work around for this?

**Comment by d4rken** [comment] 2020-07-30 10:18
That's probably it. I'm not sure if you can set the same IDs between both. I have never tried that.

You could track manually tracking pageviews by hooking into WebView callbacks.

**Comment by hannahcx** [comment] 2020-07-30 10:31
Yes, we've done that now, and this will allow us to capture time in app and also pages viewed; however, for more complex functionality like "clicks" and "errors seen" this will be too tricky for us to capture via webview callbacks without lots of work, so we were hoping to keep webview and app code separate but have them register as the same session in the Matamo UI.

**Comment by d4rken** [comment] 2020-07-30 10:37
That's not a use-case I've explored. You'd probably need to make sure the same IDs are used.
I'm not familiar with the JavaScript tracker. You'll have to dive into the code yourself.

**Comment by hannahcx** [comment] 2020-07-30 10:49
Same Id's used, but registered as two different sessions. Thanks anyway - needs to be resolved in the future because this is one reason why we are moving all of our apps to firebase in the future, because they handle this use case.

**Comment by peterbo** [comment] 2020-07-30 16:34
This is probably due to https://github.com/matomo-org/matomo/issues/15593 - which should be fixed with the next version.

**Comment by hannahcx** [comment] 2020-07-30 16:45
Ah yes, thank you, it's because of the "two sessions for a unique ID" that the app session (native pages) are registered as only being in the app for one second - if this is resolved then there potentially will be no issue, and we won't have to move to firebase!

**Closed** 2022-06-28 15:36 UTC
Labels: enhancement, help/discussion wanted
